export const ALERT_ENGINE_VERSION = "0.7.0-hypothesis.1" as const;
export type AlertType = "DECISION_CHANGE" | "REGIME_CHANGE" | "MARKET_STRUCTURE_RISK" | "DATA_QUALITY";
export type AlertSeverity = "INFO" | "WARNING" | "CRITICAL";
export type AlertDirection = "IMPROVING" | "DETERIORATING" | "CHANGED";
export type EvaluationMode = "LIVE" | "HISTORICAL";
export interface DecisionAlertInput {eventId:string;decisionSnapshotId:string;assetId:string;assetSymbol:"BTC"|"ETH";occurredAt:string;previousDecision:string;decision:string;previousMacroScore:number;macroScore:number;previousCryptoScore:number;cryptoScore:number;previousMarketStructure:string;marketStructure:string;previousAssetScore:number;assetScore:number;riskOverride:string}
export interface DataQualityAlertInput {eventId:string;indicatorCode:string;occurredAt:string;eventType:string;severity:string}
export interface AlertCandidate {alertType:AlertType;severity:AlertSeverity;direction:AlertDirection;fingerprint:string;title:string;message:string;occurredAt:string;assetId:string|null;decisionSnapshotId:string|null;payload:Record<string,unknown>}
export interface RecentAlert {fingerprint:string;alertType:AlertType;assetId:string|null;createdAt:string}
export interface AlertSelection {accepted:AlertCandidate[];suppressed:Array<{candidate:AlertCandidate;reason:"DUPLICATE"|"COOLDOWN"}>}
const decisionRank:Record<string,number>={DEFENSIVE:-2,RISK_REDUCTION:-1,NEUTRAL:0,ACCUMULATION:1,STRONG_ACCUMULATION:2};
const marketRisk:Record<string,number>={HEALTHY:0,STRESSED:1,ELEVATED_RISK:1,CAPITULATION:2,OVERHEATED:2};
const direction=(before:number,after:number):AlertDirection=>after>before?"IMPROVING":after<before?"DETERIORATING":"CHANGED";
export function decisionAlert(input:DecisionAlertInput,mode:EvaluationMode):AlertCandidate|null{if(mode==="HISTORICAL")return null;const changes:string[]=[];if(input.previousMacroScore!==input.macroScore)changes.push(`macro ${input.previousMacroScore} → ${input.macroScore}`);if(input.previousCryptoScore!==input.cryptoScore)changes.push(`crypto credit ${input.previousCryptoScore} → ${input.cryptoScore}`);if(input.previousMarketStructure!==input.marketStructure)changes.push(`market structure ${input.previousMarketStructure} → ${input.marketStructure}`);if(input.previousAssetScore!==input.assetScore)changes.push(`asset ${input.previousAssetScore} → ${input.assetScore}`);const decisionChanged=input.previousDecision!==input.decision;const riskBefore=marketRisk[input.previousMarketStructure]??0;const riskAfter=marketRisk[input.marketStructure]??0;const riskChanged=riskBefore!==riskAfter||input.riskOverride!=="NONE";if(!decisionChanged&&!riskChanged&&changes.length===0)return null;const alertType:AlertType=decisionChanged?"DECISION_CHANGE":riskChanged?"MARKET_STRUCTURE_RISK":"REGIME_CHANGE";const alertDirection=decisionChanged?direction(decisionRank[input.previousDecision]??0,decisionRank[input.decision]??0):riskChanged?direction(riskAfter,riskBefore):"CHANGED";const severity:AlertSeverity=input.riskOverride!=="NONE"||riskAfter===2?"CRITICAL":alertDirection==="DETERIORATING"?"WARNING":"INFO";const title=decisionChanged?`${input.assetSymbol}: ${input.previousDecision} → ${input.decision}`:alertType==="MARKET_STRUCTURE_RISK"?`${input.assetSymbol}: market structure gewijzigd`:`${input.assetSymbol}: regime gewijzigd`;return{alertType,severity,direction:alertDirection,fingerprint:`alert-v1:${alertType}:${input.assetSymbol}:${input.eventId}`,title,message:changes.length?changes.join("; "):input.riskOverride!=="NONE"?`Risk override: ${input.riskOverride}`:"Materiële modelwijziging.",occurredAt:input.occurredAt,assetId:input.assetId,decisionSnapshotId:input.decisionSnapshotId,payload:{engineVersion:ALERT_ENGINE_VERSION,previousDecision:input.previousDecision,decision:input.decision,riskOverride:input.riskOverride,changes}}}
export function dataQualityAlert(input:DataQualityAlertInput,mode:EvaluationMode):AlertCandidate|null{if(mode==="HISTORICAL")return null;const severity:AlertSeverity=input.severity==="CRITICAL"?"CRITICAL":"WARNING";return{alertType:"DATA_QUALITY",severity,direction:"DETERIORATING",fingerprint:`alert-v1:DATA_QUALITY:${input.eventId}`,title:`Datakwaliteit: ${input.indicatorCode}`,message:`${input.eventType} vereist aandacht.`,occurredAt:input.occurredAt,assetId:null,decisionSnapshotId:null,payload:{engineVersion:ALERT_ENGINE_VERSION,eventId:input.eventId,indicatorCode:input.indicatorCode,eventType:input.eventType}}}
export function selectAlerts(candidates:AlertCandidate[],recent:RecentAlert[],now:Date,cooldownHours=24):AlertSelection{const accepted:AlertCandidate[]=[];const suppressed:AlertSelection["suppressed"]=[];const known=new Set(recent.map(item=>item.fingerprint));const cutoff=now.getTime()-cooldownHours*3_600_000;for(const candidate of candidates){if(known.has(candidate.fingerprint)){suppressed.push({candidate,reason:"DUPLICATE"});continue;}const cooling=[...recent,...accepted.map(item=>({fingerprint:item.fingerprint,alertType:item.alertType,assetId:item.assetId,createdAt:item.occurredAt}))].some(item=>item.alertType===candidate.alertType&&item.assetId===candidate.assetId&&new Date(item.createdAt).getTime()>cutoff);if(cooling){suppressed.push({candidate,reason:"COOLDOWN"});continue;}accepted.push(candidate);known.add(candidate.fingerprint);}return{accepted,suppressed}}
