import{createClient}from"@supabase/supabase-js";
const required=(name:string)=>{const value=process.env[name];if(!value)throw new Error(`${name} is missing`);return value};
const client=createClient(required("NEXT_PUBLIC_SUPABASE_URL"),required("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false,autoRefreshToken:false}});const startedAt=new Date();
const{data:run,error:runError}=await client.from("model_runs").insert({run_type:"TRUST_CAPTURE",run_mode:"SHADOW",status:"RUNNING",started_at:startedAt.toISOString(),engine_version:"0.7.0-hypothesis.1"}).select("id").single();if(runError)throw new Error(`model run start failed: ${runError.code} ${runError.message}`);
try{const[{data:trust,error:trustError},{count:decisions,error:decisionError},{count:transitions,error:transitionError},{count:alerts,error:alertError},{data:latestRun,error:latestRunError}]=await Promise.all([
 client.from("trust_status").select("*").single(),client.from("decision_snapshots").select("id",{count:"exact",head:true}),client.from("decision_snapshots").select("id",{count:"exact",head:true}).not("previous_state","is",null),client.from("alerts").select("id",{count:"exact",head:true}),client.from("ingestion_runs").select("job_type,status,started_at,completed_at,records_received,records_valid").order("started_at",{ascending:false}).limit(1).maybeSingle()]);
 if(trustError||decisionError||transitionError||alertError||latestRunError)throw(trustError||decisionError||transitionError||alertError||latestRunError);
 const now=new Date();const latest=trust.latest_decision_at?new Date(trust.latest_decision_at):null;const row={captured_at:now.toISOString(),observation_date:now.toISOString().slice(0,10),model_validation_status:"UNVALIDATED",fresh_indicators:trust.fresh_indicators,stale_indicators:trust.stale_indicators,missing_indicators:trust.missing_indicators,open_quality_events:trust.open_quality_events,decision_snapshots:decisions??0,decision_transitions:transitions??0,alert_count:alerts??0,latest_decision_at:trust.latest_decision_at,pipeline_delay_seconds:latest?Math.max(0,Math.round((now.getTime()-latest.getTime())/1000)):null,details:{decisionFreshness:trust.decision_freshness,latestIngestionRun:latestRun}};
 const{error}=await client.from("trust_observations").upsert(row,{onConflict:"observation_date"});if(error)throw error;await client.from("model_runs").update({status:"SUCCEEDED",completed_at:new Date().toISOString(),records_evaluated:1,metadata:{observationDate:row.observation_date}}).eq("id",run.id);console.log(JSON.stringify(row,null,2));
}catch(error){const message=error instanceof Error?error.message:"Unknown trust capture failure";await client.from("model_runs").update({status:"FAILED",completed_at:new Date().toISOString(),error:message}).eq("id",run.id);throw error}
