import type { DataContract, PhaseOneIndicator } from "./types";

export const DATA_CONTRACTS: Readonly<Record<PhaseOneIndicator, DataContract>> =
  {
    EUR_USD:{indicator:"EUR_USD",unit:"usd_per_eur",minimum:0.5,maximum:2,maxPlausibleChangePercent:10,expectedIntervalSeconds:86_400,staleAfterSeconds:345_600,reconciliationTolerancePercent:1,canonicalProvider:"ecb-fx"},
    BTC_USD: {
      indicator: "BTC_USD",
      unit: "usd",
      minimum: 100,
      maximum: 2_000_000,
      maxPlausibleChangePercent: 35,
      expectedIntervalSeconds: 900,
      staleAfterSeconds: 1_800,
      reconciliationTolerancePercent: 1,
      canonicalProvider: "coingecko",
      fallbackProvider: "twelve-data",
    },
    ETH_USD: {
      indicator: "ETH_USD",
      unit: "usd",
      minimum: 1,
      maximum: 200_000,
      maxPlausibleChangePercent: 40,
      expectedIntervalSeconds: 900,
      staleAfterSeconds: 1_800,
      reconciliationTolerancePercent: 1,
      canonicalProvider: "coingecko",
      fallbackProvider: "twelve-data",
    },
    DXY: {
      indicator: "DXY",
      unit: "index_points",
      minimum: 50,
      maximum: 200,
      maxPlausibleChangePercent: 10,
      expectedIntervalSeconds: 3_600,
      staleAfterSeconds: 14_400,
      reconciliationTolerancePercent: 0.5,
      canonicalProvider: "ice-data-api",
    },
    DXY_PROXY_ECB: {
      indicator: "DXY_PROXY_ECB",
      unit: "index_points",
      minimum: 50,
      maximum: 200,
      maxPlausibleChangePercent: 10,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 345_600,
      reconciliationTolerancePercent: 2,
      canonicalProvider: "ecb-dxy-proxy",
    },
    US_BROAD_DOLLAR_INDEX: {
      indicator: "US_BROAD_DOLLAR_INDEX",
      unit: "index_points",
      minimum: 50,
      maximum: 200,
      maxPlausibleChangePercent: 10,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 345_600,
      reconciliationTolerancePercent: 2,
      canonicalProvider: "fred-broad-dollar",
    },
    US10Y_REAL: {
      indicator: "US10Y_REAL",
      unit: "percent",
      minimum: -10,
      maximum: 20,
      maxPlausibleChangePercent: 100,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 345_600,
      reconciliationTolerancePercent: 5,
      canonicalProvider: "fred",
    },
    STABLECOIN_SUPPLY_USD: {
      indicator: "STABLECOIN_SUPPLY_USD",
      unit: "usd",
      minimum: 1_000_000_000,
      maximum: 10_000_000_000_000,
      maxPlausibleChangePercent: 10,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 129_600,
      reconciliationTolerancePercent: 2,
      canonicalProvider: "defillama",
    },
    BTC_ETF_NET_FLOW_USD: {
      indicator: "BTC_ETF_NET_FLOW_USD",
      unit: "usd",
      minimum: -10_000_000_000,
      maximum: 10_000_000_000,
      maxPlausibleChangePercent: 100_000,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 259_200,
      reconciliationTolerancePercent: 5,
      canonicalProvider: "sosovalue",
    },
    ETH_ETF_NET_FLOW_USD: {
      indicator: "ETH_ETF_NET_FLOW_USD",
      unit: "usd",
      minimum: -10_000_000_000,
      maximum: 10_000_000_000,
      maxPlausibleChangePercent: 100_000,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 259_200,
      reconciliationTolerancePercent: 5,
      canonicalProvider: "sosovalue",
    },
    US_NET_LIQUIDITY_USD: {
      indicator: "US_NET_LIQUIDITY_USD",
      unit: "usd_billions",
      minimum: -5_000,
      maximum: 20_000,
      maxPlausibleChangePercent: 20,
      expectedIntervalSeconds: 604_800,
      expectedAlignmentSeconds: 518_400,
      staleAfterSeconds: 864_000,
      reconciliationTolerancePercent: 2,
      canonicalProvider: "fred-liquidity",
    },
    GLOBAL_LIQUIDITY_USD: {
      indicator: "GLOBAL_LIQUIDITY_USD",
      unit: "usd_billions",
      minimum: 1_000,
      maximum: 100_000,
      maxPlausibleChangePercent: 15,
      expectedIntervalSeconds: 2_678_400,
      staleAfterSeconds: 5_356_800,
      reconciliationTolerancePercent: 3,
      canonicalProvider: "fred-global-liquidity",
    },
    DEFI_ACTIVE_LOANS_USD: {
      indicator: "DEFI_ACTIVE_LOANS_USD",
      unit: "usd",
      minimum: 0,
      maximum: 1_000_000_000_000,
      maxPlausibleChangePercent: 35,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 172_800,
      reconciliationTolerancePercent: 5,
      canonicalProvider: "defillama-loans",
    },
    BTC_MVRV: {
      indicator: "BTC_MVRV",
      unit: "ratio",
      minimum: 0,
      maximum: 20,
      maxPlausibleChangePercent: 50,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 172_800,
      reconciliationTolerancePercent: 5,
      canonicalProvider: "bgeometrics",
    },
    BTC_REALIZED_LOSSES_USD: {
      indicator: "BTC_REALIZED_LOSSES_USD",
      unit: "usd",
      minimum: 0,
      maximum: 100_000_000_000,
      maxPlausibleChangePercent: 10_000,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 172_800,
      reconciliationTolerancePercent: 10,
      canonicalProvider: "bgeometrics",
    },
    BTC_PERPETUAL_OI_USD: {
      indicator: "BTC_PERPETUAL_OI_USD",
      unit: "usd",
      minimum: 0,
      maximum: 1_000_000_000_000,
      maxPlausibleChangePercent: 50,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 172_800,
      reconciliationTolerancePercent: 5,
      canonicalProvider: "coinalyze",
    },
    BTC_MARKET_CAP_USD: {
      indicator: "BTC_MARKET_CAP_USD",
      unit: "usd",
      minimum: 1_000_000_000,
      maximum: 100_000_000_000_000,
      maxPlausibleChangePercent: 40,
      expectedIntervalSeconds: 86_400,
      staleAfterSeconds: 172_800,
      reconciliationTolerancePercent: 3,
      canonicalProvider: "bgeometrics",
      fallbackProvider: "coingecko-market-cap",
    },
  };
