begin;
alter table public.alerts add column direction text not null default 'CHANGED' check(direction in('IMPROVING','DETERIORATING','CHANGED'));
alter table public.alerts add column event_at timestamptz not null default now();
alter table public.alerts add column payload jsonb not null default '{}'::jsonb check(jsonb_typeof(payload)='object');
alter table public.alerts add column read_at timestamptz;
alter table public.alerts add column email_status text not null default 'DISABLED' check(email_status in('DISABLED','PENDING','DELIVERED','FAILED'));
alter table public.alerts add column email_provider_id text;
create index alerts_inbox_lookup on public.alerts(user_id,created_at desc);
create index alerts_cooldown_lookup on public.alerts(user_id,alert_type,asset_id,created_at desc);
create table public.notification_preferences(user_id uuid primary key references auth.users(id)on delete cascade,in_app_enabled boolean not null default true,email_enabled boolean not null default false,cooldown_hours integer not null default 24 check(cooldown_hours between 1 and 168),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.notification_preferences(user_id)select id from auth.users on conflict(user_id)do nothing;
alter table public.notification_preferences enable row level security;
create policy "users read own notification preferences" on public.notification_preferences for select to authenticated using((select auth.uid())=user_id);
create policy "users insert own notification preferences" on public.notification_preferences for insert to authenticated with check((select auth.uid())=user_id);
create policy "users update own notification preferences" on public.notification_preferences for update to authenticated using((select auth.uid())=user_id)with check((select auth.uid())=user_id);
create table public.alert_engine_state(id boolean primary key default true check(id),live_since timestamptz not null,engine_version text not null,updated_at timestamptz not null default now());
insert into public.alert_engine_state(id,live_since,engine_version)values(true,now(),'0.7.0-hypothesis.1');
alter table public.alert_engine_state enable row level security;
insert into public.engine_versions(version,configuration,description,activated_at)values('0.7.0-hypothesis.1','{"model":"v3","phase":8,"alertEngineActive":true,"decisionEngineVersion":"0.6.0-hypothesis.1","historicalAlerts":false,"defaultCooldownHours":24,"channels":["IN_APP","EMAIL"],"emailProvider":"RESEND","assumptionStatus":"HYPOTHESIS"}','Deterministic material-change alerts with live-mode gate, database and provider idempotency, cooldown, in-app inbox and optional email.',now())on conflict(version)do nothing;
create or replace view public.notification_inbox with(security_invoker=true)as select al.id,al.alert_type,al.severity,al.direction,al.title,al.message,al.event_at,al.created_at,al.read_at,al.delivery_status,al.email_status,al.decision_snapshot_id,a.symbol from public.alerts al left join public.assets a on a.id=al.asset_id;
grant select on public.notification_inbox to authenticated;
commit;
