begin;
create or replace function public.complete_guided_onboarding(p_experience text,p_base_currency text,p_objective text,p_horizon integer,p_max_drawdown numeric,p_min_cash numeric,p_max_asset numeric,p_turnover numeric,p_cadence text,p_assets text[],p_starting_capital numeric)
returns void language plpgsql security invoker set search_path=public as $$declare uid uuid:=auth.uid();v_account_id uuid;begin
 if uid is null then raise exception 'not authenticated';end if;
 if p_experience not in('GUIDED','ADVANCED')or p_base_currency not in('EUR','USD')or p_objective not in('CAPITAL_PRESERVATION','BALANCED','GROWTH')or p_cadence not in('WEEKLY','MONTHLY','QUARTERLY')then raise exception 'invalid enum';end if;
 if p_horizon not between 3 and 240 or p_max_drawdown not between 1 and 80 or p_min_cash not between 0 and 99 or p_max_asset not between 1 and 100 or p_min_cash+p_max_asset>100 or p_turnover not between 0 and 2000 or p_starting_capital not between 1000 and 100000000 then raise exception 'invalid limits';end if;
 if cardinality(p_assets)=0 or p_assets <@ array['BTC','ETH']::text[] is not true then raise exception 'invalid assets';end if;
 insert into public.user_product_settings(user_id,experience_level,onboarding_completed_at,disclaimer_accepted_at,updated_at)values(uid,p_experience,now(),now(),now())on conflict(user_id)do update set experience_level=excluded.experience_level,onboarding_completed_at=excluded.onboarding_completed_at,disclaimer_accepted_at=excluded.disclaimer_accepted_at,updated_at=now();
 insert into public.investor_mandates(user_id,version,base_currency,objective,horizon_months,maximum_drawdown_percent,minimum_cash_percent,maximum_asset_weight_percent,annual_turnover_budget_percent,rebalance_cadence,allowed_assets,evidence_status,effective_at)values(uid,'guided-v1-'||clock_timestamp(),p_base_currency,p_objective,p_horizon,p_max_drawdown,p_min_cash,p_max_asset,p_turnover,p_cadence,p_assets,'SHADOW',now());
 select id into v_account_id from public.portfolio_accounts where user_id=uid and name='Paper startportfolio';if v_account_id is null then insert into public.portfolio_accounts(user_id,name,base_currency,account_type)values(uid,'Paper startportfolio',p_base_currency,'MANUAL')returning id into v_account_id;end if;
 if not exists(select 1 from public.portfolio_transactions where user_id=uid and account_id=v_account_id and external_reference='ONBOARDING_INITIAL_CAPITAL')then insert into public.portfolio_transactions(user_id,account_id,transaction_type,symbol,quantity,unit_price,fee,executed_at,external_reference,notes)values(uid,v_account_id,'DEPOSIT','CASH',p_starting_capital,0,0,now(),'ONBOARDING_INITIAL_CAPITAL','Fictief startkapitaal uit onboarding');end if;
 insert into public.paper_portfolios(user_id,protocol_version,base_currency,started_at,status,initial_capital)values(uid,'cas-shadow-protocol-v1',p_base_currency,now(),'ACTIVE',p_starting_capital)on conflict(user_id,protocol_version)do nothing;
end$$;
commit;
